# Generated by Django 4.0.4 on 2022-06-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('status', models.CharField(choices=[('ERROR', 'error'), ('SUCCESS', 'success'), ('INFO', 'info')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('notifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.notification')),
            ],
        ),
    ]
